### ISSUE TITLE
您好，第一步出现 git@github.com: Permission denied (publickey) 问题

### ISSUE THREAD

**Issue by xes5566** [sarkrui/Eudic-for-Mac#1]
macdemacbook:~ mac$ git clone git@github.com:sarkrui/Eudic-for-Mac.git
Cloning into 'Eudic-for-Mac'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by sarkrui** [comment]
已修复
