### ISSUE TITLE
配置缓存全清了一遍,还是出现了'试用已过期,请重新注册的问题'

### ISSUE THREAD

**Issue by glitterlip** [sarkrui/Eudic-for-Mac#2]
配置缓存全清了一遍,还是出现了'试用已过期,请重新注册的问题'
.....可能是新版又改了什么配置,导致试用过的记录一直清不掉

**Comment by sarkrui** [comment]
已更新脚本，用 App Cleaner 把 Eudic 清理干净，重新 pull 一下，再安装。

**Comment by sarkrui** [comment]
再尝试一下？
