### ISSUE TITLE
不断闪退

### ISSUE THREAD

**Issue by Panda-Ma** [sarkrui/Eudic-for-Mac#5]
![ff0c71295d41a4bb3b82fdd57d9b5e39](https://user-images.githubusercontent.com/83866306/134905913-d36fbd97-57f8-4440-a876-f40c9c4f62d3.png)

**Comment by Panda-Ma** [comment]
不断闪退 但我不知道怎么解决 只能不用了

**Comment by sarkrui** [comment]
@KillQueen-hello 你可以试试用 [AppCleaner](https://freemacsoft.net/appcleaner/)把 Eudic 完全删除干净后，重启电脑，再跑与一下

> export LANG="zh_CN.UTF-8" && sh -c "$(curl -fsSL https://cdn.jsdelivr.net/gh/sarkrui/Eudic-for-Mac@master/Eudic_cn.sh)"

也可以淘宝10块钱买个合租的账号下载 App Store 版本的
